"""
IntroPlan Navigation Baseline — Full Pipeline Runner

Implements the IntroPlan decision pipeline for outdoor robot navigation:

  1. Load the navigation knowledge base (calibration scenarios + reasonings)
  2. Given a new scenario (instruction + terrain description):
     a. Generate candidate options A/B/C/D via Claude
     b. Retrieve K similar past examples from the knowledge base
     c. Ask Claude to reason introspectively about each option
     d. Extract per-option confidence scores
     e. Apply conformal prediction → prediction set
     f. |set| == 1 → ACT   |set| > 1 → ASK

This is the baseline as described in:
  Liang et al., "Introspective Planning: Aligning Robots' Uncertainty with
  Inherent Task Ambiguity," NeurIPS 2024. arXiv:2402.06529
Adapted from Mobile Manipulation → Outdoor Navigation Under Uncertainty.
"""

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

import yaml

from baselines.introplan.conformal_predictor import (
    ConformalPredictor,
    extract_option_confidences,
    normalize_confidences,
)
from baselines.introplan.knowledge_base import NavigationKnowledgeBase
from baselines.introplan.llm_interface import LLMInterface
from baselines.introplan.metrics import MetricsCalculator, ScenarioResult
from baselines.introplan.navigation_prompts import (
    OPTION_DESCRIPTIONS,
    format_candidate_options_prompt,
    format_introspective_predict_prompt,
)


@dataclass
class NavigationScenario:
    """One input scenario for the IntroPlan runner."""
    scenario_id: str
    instruction: str
    terrain_description: str
    uncertainty_type: int
    correct_option: str
    options: Optional[Dict[str, str]] = None  # If None, generated by LLM


@dataclass
class IntroPlanDecision:
    """Output from one IntroPlan inference call."""
    scenario_id: str
    options: Dict[str, str]
    option_confidences: Dict[str, float]
    prediction_set: List[str]
    robot_decision: str          # "A"/"B"/"C"/"D" or "ASK"
    llm_reasoning: Dict          # Raw LLM response dict
    retrieved_example_ids: List[str]


class IntroPlanRunner:
    """
    End-to-end IntroPlan navigation baseline runner.

    Supports two modes:
      - run_scenario():    Single scenario, returns IntroPlanDecision
      - run_evaluation():  Full evaluation loop over a scenario list, returns metrics
    """

    def __init__(
        self,
        config_path: str,
        llm: Optional[LLMInterface] = None,
    ):
        """
        Args:
            config_path: Path to baselines/introplan/config.yaml
            llm:         Optional pre-constructed LLMInterface (useful for testing with mocks)
        """
        with open(config_path) as f:
            self.config = yaml.safe_load(f)

        self._llm = llm or LLMInterface(
            model=self.config.get("llm", {}).get("model", "claude-sonnet-4-6"),
            max_tokens=self.config.get("llm", {}).get("max_tokens", 1024),
            temperature=self.config.get("llm", {}).get("temperature", 0.0),
        )

        kb_path = self.config.get("knowledge_base", {}).get(
            "path", "baselines/introplan/data/nav_calibration.json"
        )
        self._kb = NavigationKnowledgeBase.from_json(kb_path)

        alpha = self.config.get("conformal", {}).get("alpha", 0.15)
        self._predictor = ConformalPredictor(alpha=alpha)
        self._top_k = self.config.get("knowledge_base", {}).get("top_k", 3)

    def run_scenario(self, scenario: NavigationScenario) -> IntroPlanDecision:
        """
        Run the full IntroPlan pipeline for one scenario.

        Args:
            scenario: The input navigation scenario.

        Returns:
            IntroPlanDecision with prediction set and robot decision.
        """
        # Step 1: Get or generate candidate options
        options = scenario.options or self._generate_options(scenario)

        # Step 2: Retrieve similar past examples from knowledge base
        similar = self._kb.retrieve_as_dicts(
            instruction=scenario.instruction,
            terrain_description=scenario.terrain_description,
            top_k=self._top_k,
        )
        retrieved_ids = [ex.get("entry_id", "") for ex in similar]

        # Step 3: Ask Claude for introspective reasoning + prediction
        prompt = format_introspective_predict_prompt(
            instruction=scenario.instruction,
            terrain_description=scenario.terrain_description,
            options=options,
            retrieved_examples=similar,
        )
        llm_response = self._llm.predict_json(prompt)

        # Step 4: Extract per-option confidences from LLM response
        raw_confidences = extract_option_confidences(llm_response)
        confidences = normalize_confidences(raw_confidences)

        # Step 5: Apply conformal prediction (requires prior calibration)
        if self._predictor.tau is not None:
            prediction_set = self._predictor.predict_set(confidences)
        else:
            # No calibration yet — use direct prediction (highest confidence wins)
            best = max(confidences, key=confidences.get)
            prediction_set = [best]

        # Step 6: Determine robot decision
        robot_decision = "ASK" if len(prediction_set) != 1 else prediction_set[0]

        return IntroPlanDecision(
            scenario_id=scenario.scenario_id,
            options=options,
            option_confidences=confidences,
            prediction_set=prediction_set,
            robot_decision=robot_decision,
            llm_reasoning=llm_response,
            retrieved_example_ids=retrieved_ids,
        )

    def calibrate(self, calibration_scenarios: List[NavigationScenario]) -> float:
        """
        Run calibration: collect LLM predictions on labeled scenarios,
        then compute the conformal threshold tau.

        Args:
            calibration_scenarios: Scenarios with known correct_option labels.

        Returns:
            The computed tau threshold.
        """
        for scenario in calibration_scenarios:
            decision = self.run_scenario(scenario)
            self._predictor.record_calibration(
                option_confidences=decision.option_confidences,
                correct_option=scenario.correct_option,
            )
        return self._predictor.calibrate()

    def run_evaluation(
        self,
        test_scenarios: List[NavigationScenario],
    ) -> Dict:
        """
        Run the full evaluation loop on a list of test scenarios.

        Args:
            test_scenarios: Scenarios with known correct_option labels.

        Returns:
            Metrics dict from MetricsCalculator.summary().
        """
        calc = MetricsCalculator()

        for scenario in test_scenarios:
            decision = self.run_scenario(scenario)
            result = ScenarioResult(
                scenario_id=scenario.scenario_id,
                correct_option=scenario.correct_option,
                prediction_set=decision.prediction_set,
                robot_decision=decision.robot_decision,
            )
            calc.add(result)

        return calc.summary()

    def _generate_options(self, scenario: NavigationScenario) -> Dict[str, str]:
        """
        Ask Claude to generate candidate options for a scenario.
        Falls back to default option descriptions if LLM call fails.
        """
        prompt = format_candidate_options_prompt(
            instruction=scenario.instruction,
            terrain_description=scenario.terrain_description,
            uncertainty_type=scenario.uncertainty_type,
        )
        try:
            options = self._llm.predict_json(prompt)
            # Ensure all 4 options are present
            for label in ["A", "B", "C", "D"]:
                if label not in options:
                    options[label] = OPTION_DESCRIPTIONS[label]
            return options
        except Exception:
            return dict(OPTION_DESCRIPTIONS)


def load_scenarios_from_json(path: str) -> List[NavigationScenario]:
    """
    Load a list of NavigationScenario objects from a JSON file.

    JSON format (matches nav_calibration.json and nav_test.json):
    [
      {
        "entry_id": "nav_001",
        "instruction": "...",
        "terrain_description": "...",
        "uncertainty_type": 2,
        "options": {"A": "...", "B": "...", "C": "...", "D": "..."},
        "correct_option": "B"
      }, ...
    ]
    """
    with open(path) as f:
        data = json.load(f)

    scenarios = []
    for d in data:
        scenarios.append(NavigationScenario(
            scenario_id=d.get("entry_id", d.get("scenario_id", "")),
            instruction=d["instruction"],
            terrain_description=d["terrain_description"],
            uncertainty_type=d["uncertainty_type"],
            correct_option=d["correct_option"],
            options=d.get("options"),
        ))
    return scenarios
